### PR TITLE
Implemented convertion from NSLocalizedString into structured enums

### LINKED ISSUE #24: Convert NSLocalizedStrings into structured enums
This proposal will enable developer to use enum multi levels to find the right localized string instead needs to copy from .strings and paste into code.

**Example**
From this:
```
let product = NSLocalizedString("Radar.Product", comment: "")
```

into this:
```
let product = Localizable.Radar.product.localized
```

Convert in views controllers:
- [x] LoginCoordinator.swift
- [x] LoginError.swift
- [x] RadarCoordinator.swift
- [x] RadarViewController.swift
- [x] SettingsViewController.swift

### PR DESCRIPTION
**Pull request by unnamedd**
closes #24

### CODE REVIEW

**Comment by florianbuerger** [comment]
Thanks, did you use SwiftGen or something similar? If so, would be great if there would also be a Build Phase to automatically create the enums.

**Comment by unnamedd** [comment]
@florianbuerger no. I did it all myself. Any tool like SwiftGen or similar will create these enums in multi-levels. I believe that these multi-levels are the key to make it useful when we are using throughout the code.

This kind of thing just needs to be done when we are working on something new, I'm sure that we won't need to care about an automatic generation. Thoughts ?

**Comment by unnamedd** [comment]
@florianbuerger the conflicts are gone! ;)

**Comment by unnamedd** [comment]
@florianbuerger any thoughts about this PR ? Is it insteresting ?

**Comment by florianbuerger** [comment]
Hey, so sorry for my late reply.

I think you are right. We'll keep the manual version for now. If for whatever reason there are tons of new strings, `swiftgen` could be an option.

**Comment by unnamedd** [comment]
@florianbuerger yeah. Isn't hard to create these items manually, to be honest, I prefer to do this like that. Will only be a good option, if these tools could understand the use of our separador (`.`) and create these enums, but in the end, we will need to check it to ensure that is all okay.

**Comment by florianbuerger** [comment]
Oh `swiftgen` does understand them. It creates nested enums as well 😉

**Comment by unnamedd** [comment]
Really ?! That's awesome! I'll take a look on it!

**Pull request merged**
